x1 = float(input("masukkan x1 : "))
y1 = float(input("masukkan y1 : "))
x2 = float(input("masukkan x2 : "))
y2 = float(input("masukkan y2 : "))
m = (y2-y1)/(x2-x1)
c = (y1*x2 - x1*y2)/(x2-x1)
print("y=", m,"x +", c)
